import 'package:flutter/material.dart';

final firstNameController = TextEditingController();
final lastNameController = TextEditingController();
final emailController = TextEditingController();
final phoneNumberController = TextEditingController();
final passwordController = TextEditingController();
final confirmPasswordController = TextEditingController();
final streetAddressController = TextEditingController();
final cityController = TextEditingController();
final postalCodeController = TextEditingController();
final modelController = TextEditingController();
final imageUrlController = TextEditingController();
final socController = TextEditingController();
final ramController = TextEditingController();
final storageController = TextEditingController();
final screenSizeController = TextEditingController();
final batteryController = TextEditingController();
final cameraController = TextEditingController();
final priceController = TextEditingController();
final stockController = TextEditingController();
final sarController = TextEditingController();
