// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0jl24nb9EsnGnGvu0IKs6nN0a4bYFSl0',
    appId: '1:435676149986:web:40fca7cdaa7c2f066986bb',
    messagingSenderId: '435676149986',
    projectId: 'flutter-ecommerce-website-demo',
    authDomain: 'flutter-ecommerce-website-demo.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-website-demo.appspot.com',
    measurementId: 'G-M8V7JGW66F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYauzckV-cWO6l92X1ejQ8d1YexiRpiK0',
    appId: '1:435676149986:android:a5d7635e147667ae6986bb',
    messagingSenderId: '435676149986',
    projectId: 'flutter-ecommerce-website-demo',
    storageBucket: 'flutter-ecommerce-website-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4lL_eMNk5H4l0tH2VnYr6C-qL5YcfdWA',
    appId: '1:435676149986:ios:3d243e2b815447486986bb',
    messagingSenderId: '435676149986',
    projectId: 'flutter-ecommerce-website-demo',
    storageBucket: 'flutter-ecommerce-website-demo.appspot.com',
    iosClientId: '435676149986-bb90pvr327jtuss2eovgve7rlmk29bvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerceWebsiteDemo',
  );
}
